# Este é o cabeçalho da secção. É OBRIGATÓRIO e deve ser exatamente este.
# O seu código Python procura por "firebase_credentials".
[firebase_credentials]
type = "service_account"
project_id = "fitpro-app-e90d9"
private_key_id = "8b89942997bb5e6ad1a9b7178e5e80a3fd71426c"
# A chave privada deve estar entre aspas triplas para lidar com as quebras de linha.
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCidxAcdolofZ2T
S5QauTNstaI9VKgNuXxVmR/8/+4eSXB7S7ZYQRhasBG3yftv9MHrT9VFd36wwYlr
GaAbWoZYTLqzUJWu4NcQ7Tl2SmIe7rrmqjTwYs49SMO1vGqurPXopqslABu5OO3y
gj785m8RYf/XTUIZ4nJQSRrcb5grs0cOoG//jLpRqoKSbnVt6jq/p86fQiChvgQJ
UPUAsYSYH8drdUQPdagyLPzD6O4xDeDYBTiDjDrRTpE8dOzrkoriAp6EzkV8cI9z
470xG4RwJk45wwYY/d0V8gZCwoHUqJ+EAaCjMJBK9ExDbVaBm1Te+70THX6bJJXU
5MDaGglzAgMBAAECggEACU/CDtX4acW+JBtFbmnfYBBIL5p/iBg+eRJHenlMs4dJ
n1ENyKC9sMzwmjqrlfu1DzPKXHeAPZWjttpUI901xmMEPF/9BEK2V0drCLQAsn2Q
tsTz0QDiVmVD2lGydGqALNWiPE+orYTTln4PXPCNvLUdZ1o+1KIqI4UQUtwOhuQu
ZZLd4KahpWQt1s7c4c8EmJKK5oA63XNMsrEgRb/drei7gIaEfvcodPJqCJUqsQB3
GavuuciYejDs8ljC+ey4ueORNn8j5CS2JxSKKxNQIBvmP8uilLK7q4dKzAMDD4PP
0CGvY/KxgAEy67dXFmvy9htbTLGtVS6h19AIbHB0uQKBgQDStZ6fex/c56qWazkF
4I+kkPrNi/2I6pf6rMJI/v1NAv/OPB/mNkpzChoQdWszmKJ8yo6BbMJ7MjM0KQ1E
UIBHDdRdbQ7Z1Vbm7GyGmrBY6uKk+wFEOZagHdBYj/lerwJYpRFbtpHc+T3UVNUx
AnKxE0V854mMg43NPLJCrU3fVQKBgQDFYsaqwICb/BRI6V9bofhuU5eZUI6HRW3j
VQuLyrwz6uOaELQnWMNTaOWrj38SwvNWYpzzI23fb8tQa+b9OEhERyZsWkFukGQh
ZN1KfM0DBZ+y+JfpkfIAeLohY7Z8RSww0fEUKihCWqXYD+rfHCDmEJuIq0JZkrfn
mf3HtU31pwKBgQDD4Z11yyNi3GcEcOdQ5GME7NaLUTHAH75rhkETVSErf7dJBTHu
dNgfO+vhExc2nxWnBzMVdIMTviZFvkgcEu49n8illaXxsdeY039MXu/DqZBLKSET
SKoTbcPrIOUFNZLrz4Bkj0PodjgZdUe/yPPQVAcMR77iRsYDXwKk47F6BQKBgHfl
zSmxby3RDH1RjQP7Og3CJycQ4NLYYKyjXzUV/AZJWuGd3eC8sUE8Sa5Rpu29j9Rc
aFvknHwJy2VZdeFAy9z1nyhYFsDTYo9KVoVFk76PLvemu5g8d9TDgMSBbjrERdiN
3jPSe8v6hhzdZl0KGA3H7sIwzUfdsGo1hwtFXUqnAoGAJUKw7Y/zc7A1OcR2+7o7
oopPAH1eJwizx74z5Eq1XE1IFBrxKO+NO18csuMZibXdR3z9VE3bZZIutXBnfsod
OeT52SO51PsCHkn54EuxnD3MCnL59uNz/DdhB7ZsPwgtPxpaYE7djlDRtwqcyRaB
AphM91ra9Q2TCL473gUkhL0=
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@fitpro-app-e90d9.iam.gserviceaccount.com"
client_id = "115161528309148737840"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40fitpro-app-e90d9.iam.gserviceaccount.com"
universe_domain = "googleapis.com"


